### ISSUE TITLE
Weather alert sensor remains on

### ISSUE THREAD

**Issue by groenmarsmannetje** [golles/ha-knmi#6] opened 2021-09-06 13:59 UTC
## Version of the knmi custom_component

149697f

## Describe the bug
The Weather Alert binary_sensor remains on while the KNMI website doesn't show an active alert anymore.
There was a fog alert in the morning but that was revoked during the day, but it still shows as active alert without attributes.

## Debug log

```text

N/A

```

**Comment by golles** [comment] 2021-09-06 14:36
My bad, will be fixed soon

**Comment by golles** [comment] 2021-09-06 14:43
@groenmarsmannetje, please test version 1.1.1 that has just been pushed

**Comment by groenmarsmannetje** [comment] 2021-09-06 17:29
I have installed the new version. Sensor is off now. Will check coming days when it is triggered again.

**Comment by golles** [comment] 2021-09-06 17:50
I'll close this issue for now, I'm pretty convinced that it's fixed :-)
Let me know if you see this again

**Closed by golles** 2021-09-06 17:50 UTC

**Comment by groenmarsmannetje** [comment] 2021-09-18 06:18
> I'll close this issue for now, I'm pretty convinced that it's fixed :-)
> Let me know if you see this again

@golles could it be that the weather alert now doesn’t turn on anymore? I have the feeling that it doesn’t report the fog alerts in the morning that I do see with the meteoalarm integration last couple of days.

**Comment by golles** [comment] 2021-09-18 09:56
Hi @groenmarsmannetje I could indeed see this morning that https://www.knmi.nl/nederland-nu/weer/waarschuwingen was showing a code yellow for fog in some (including my) regions, but then I also checked http://weerlive.nl/api/json-data-10min.php?key=<key>&locatie=<lat>,<lng> manually and it contained:
```
{
  ...
  "alarm": "0",
  "alarmtxt": ""
}
```
So no warning...

The sensor should turn on, on anything besides `"0"` https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/binary_sensor.py#L44 so this is something with the weerlive API.

You could try contacting them and ask if there is something wrong with their API, as the KNMI website does show a warning and the API doesn't. I've contacted them once before on `post@weerlive.nl` and found them very responsive (business day).

**Comment by golles** [comment] 2021-12-16 20:23
I assumed there should be a warning due to "code geel", I've sent a message to the API supplier.

**Comment by golles** [comment] 2022-01-21 08:00
Hi @groenmarsmannetje, I got an update on my email this morning, they have fixed this issue. I can confirm see the alert is no on :-)

Sensor attribute:
```
In het hele land, met uitzondering van de kustgebieden, komt gladheid voor door bevriezing van natte weggedeelten. Hiervan kunnen verkeer en buitenactiviteiten hinder ondervinden. In de loop van de ochtend verdwijnt de gladheid.
```
