### ISSUE TITLE
Update Failed! - unexpected character

### ISSUE THREAD

**Issue by avhoboken** [golles/ha-knmi#137] opened 2024-04-15 12:18 UTC
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

The KNMI custom component generates update errors in the HA Core log:
This error originated from a custom integration.

Logger: custom_components.knmi
Source: custom_components/knmi/coordinator.py:48
integration: KNMI (documentation, issues)
First occurred: April 13, 2024 at 11:32:51 AM (70 occurrences)
Last logged: 12:27:52 PM

Update failed! - unexpected character: line 1 column 322 (char 321)
Update failed! - unexpected character: line 1 column 321 (char 320)
Update failed! - unexpected character: line 1 column 324 (char 323)
Update failed! - unexpected character: line 1 column 318 (char 317)
Update failed! - unexpected character: line 1 column 306 (char 305)

### Integration version

2.0.1

### Home Assistant version

core-2024.4.3

### Python version

3.12.2

### Home Assistant log

```shell
2024-04-14 07:00:51.850 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.shellyplug_s_894145 are missing or not currently available
2024-04-14 07:02:51.154 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 07:02:51.154 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 07:07:51.153 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 07:42:51.150 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 07:42:51.150 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 07:47:51.151 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 08:12:51.154 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 08:12:51.154 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 08:13:41.696 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2024-04-14 08:13:41.696 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_woonkamer is taking over 10 seconds
2024-04-14 08:17:51.191 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 09:12:51.148 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 09:12:51.148 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 09:17:51.154 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 09:41:52.187 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2024-04-14 09:41:52.187 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_woonkamer is taking over 10 seconds
2024-04-14 10:02:51.155 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 10:02:51.155 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 10:07:51.159 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 10:12:51.145 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 10:17:51.152 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 323 (char 322)
2024-04-14 11:02:51.156 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 11:02:51.156 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 11:07:51.155 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 11:42:12.843 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2024-04-14 11:42:12.844 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_woonkamer is taking over 10 seconds
2024-04-14 12:34:33.145 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2024-04-14 12:34:33.145 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_woonkamer is taking over 10 seconds
2024-04-14 12:56:30.527 ERROR (Thread-9) [pychromecast.socket_client] [Hub Slaapkamer(192.168.21.18):8009] Error reading from socket.
2024-04-14 12:56:30.528 WARNING (Thread-9) [pychromecast.socket_client] [Hub Slaapkamer(192.168.21.18):8009] Error communicating with socket, resetting connection
2024-04-14 12:56:30.533 ERROR (Thread-9) [pychromecast.socket_client] [Hub Slaapkamer(192.168.21.18):8009] Failed to connect to service HostServiceInfo(host='192.168.21.18', port=8009), retrying in 5.0s
2024-04-14 13:32:51.155 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 13:32:51.156 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 13:37:51.151 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 13:42:51.146 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 13:47:51.147 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 14:35:14.225 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2024-04-14 14:35:14.225 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_woonkamer is taking over 10 seconds
2024-04-14 14:52:51.146 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 14:52:51.147 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 14:57:51.154 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 321 (char 320)
2024-04-14 15:02:51.152 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 15:07:51.157 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 15:12:51.147 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 15:17:51.146 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 15:42:51.148 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 15:42:51.148 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 15:47:51.152 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 320 (char 319)
2024-04-14 16:52:51.149 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
2024-04-14 16:52:51.149 ERROR (MainThread) [custom_components.knmi] Error fetching knmi data: 
2024-04-14 16:57:51.150 ERROR (MainThread) [custom_components.knmi] Update failed! - unexpected character: line 1 column 322 (char 321)
```

**Comment by golles** [comment] 2024-04-15 12:32
Duplicate of #130

**Closed** 2024-04-19 11:51 UTC
Labels: bug
