### ISSUE TITLE
Weather warning does not take into account the location

### ISSUE THREAD

**Issue by vheijnen** [golles/ha-knmi#102] opened 2023-12-01 10:49 UTC
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

It seems the weather warning input boolean and attributes does not take into account if the warning is applicable to the location configured in the integration. Both knmi.nl and weerlive.nl currently do not show weather alerts for this region but the integration does.
![weerlive](https://github.com/golles/ha-knmi/assets/39679385/1fce382c-b902-4e5a-9eb8-aa5e65e1367b)
![knmi](https://github.com/golles/ha-knmi/assets/39679385/4a17456f-dbd7-41bf-8c7f-8cc5600d9028)
![integration](https://github.com/golles/ha-knmi/assets/39679385/3a0e693a-416c-4df0-bdcc-03b5c4088823)

### Integration version

1.6.1

### Home Assistant version

core-2023.11.3

### Python version

3.11.6

### Diagnostics

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.6",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "spook_inverse": {
      "version": "1.3.2",
      "requirements": []
    },
    "knmi": {
      "version": "1.6.1",
      "requirements": []
    },
    "spook": {
      "version": "1.3.2",
      "requirements": []
    },
    "presence_simulation": {
      "version": "3.2",
      "requirements": []
    },
    "webrtc": {
      "version": "v3.5.0",
      "requirements": []
    },
    "powercalc": {
      "version": "v1.9.8",
      "requirements": [
        "numpy>=1.21.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "knmi",
    "name": "KNMI",
    "codeowners": [
      "@golles"
    ],
    "config_flow": true,
    "documentation": "https://github.com/golles/ha-knmi/blob/main/README.md",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/golles/ha-knmi/issues",
    "version": "1.6.1",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "902dc2c2d9d4557a359f610d0f0a6ecd",
      "version": 1,
      "domain": "knmi",
      "title": "Chateau Rijnenburg",
      "data": {
        "name": "Chateau Rijnenburg",
        "latitude": "**REDACTED**",
        "longitude": "**REDACTED**",
        "api_key": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "data": {
      "plaats": "Utrecht",
      "timestamp": "1701427384",
      "time": "01-12-2023 11:43",
      "temp": "-0.6",
      "gtemp": "-3.2",
      "samenv": "Onbewolkt",
      "lv": "86",
      "windr": "NO",
      "windrgr": "44",
      "windms": "2",
      "winds": "2",
      "windk": "3.9",
      "windkmh": "7.2",
      "luchtd": "1008.1",
      "ldmmhg": "756",
      "dauwp": "-2.6",
      "zicht": "10",
      "verw": "Perioden met zon, in het noorden een winterse bui",
      "sup": "08:22",
      "sunder": "16:33",
      "image": "zonnig",
      "d0weer": "halfbewolkt",
      "d0tmax": "2",
      "d0tmin": "-2",
      "d0windk": "2",
      "d0windknp": "6",
      "d0windms": "3",
      "d0windkmh": "11",
      "d0windr": "NO",
      "d0windrgr": "44",
      "d0neerslag": "0",
      "d0zon": "69",
      "d1weer": "halfbewolkt",
      "d1tmax": "2",
      "d1tmin": "-4",
      "d1windk": "2",
      "d1windknp": "4",
      "d1windms": "2",
      "d1windkmh": "7",
      "d1windr": "ZW",
      "d1windrgr": "225",
      "d1neerslag": "30",
      "d1zon": "50",
      "d2weer": "halfbewolkt_regen",
      "d2tmax": "2",
      "d2tmin": "-3",
      "d2windk": "2",
      "d2windknp": "6",
      "d2windms": "3",
      "d2windkmh": "11",
      "d2windr": "Z",
      "d2windrgr": "180",
      "d2neerslag": "70",
      "d2zon": "30",
      "alarm": "1",
      "alarmtxt": "Vooral op lokale wegen in Friesland, Groningen en Noord-Holland is er vanochtend kans op plaatselijke gladheid door bevriezing van natte weggedeelten.  Vanavond kan het vooral in Friesland, Groningen en Noord-Holland opnieuw plaatselijk glad worden door sneeuwbuien. Komende nacht en zaterdagochtend ook door een sneeuwdek en/of bevriezing van natte weggedeelten."
    }
  }
}
```

**Comment by golles** [comment] 2023-12-01 15:37
Duplicate of #39

The API returns a nationwide message instead of any message related to the given location. There isn't much I can do about this. You could contact the supplier with this issue.

**Closed** 2023-12-07 20:27 UTC
Labels: bug
