### ISSUE TITLE
Lots of errors since 29-10

### ISSUE THREAD

**Issue by metbril** [golles/ha-knmi#100] opened 2023-10-30 19:00 UTC
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I have lots of errors (~2500) in my log file (2x 1220) since 29 October:

<img width="1103" alt="Scherm­afbeelding 2023-10-30 om 19 51 25" src="https://github.com/golles/ha-knmi/assets/559346/2b1f88e3-162c-49ab-b8cd-f59f2c3aacc3">

[knmi.txt.zip](https://github.com/golles/ha-knmi/files/13208842/knmi.txt.zip)

Sample:
```
2023-10-29 12:18:16.974 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
2023-10-29 12:18:46.972 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
2023-10-29 12:18:46.973 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
ValueError: Sensor sensor.knmi_thuis_dauwpunt has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'onb.' (<class 'str'>)
2023-10-29 12:19:16.974 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
2023-10-29 12:19:16.975 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
2023-10-29 12:19:46.974 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
```

### Integration version

1.6.1

### Home Assistant version

core-2023.10.5

### Python version

3.11.5

### Home Assistant log

```shell
2023-10-29 12:18:16.974 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
2023-10-29 12:18:46.972 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
2023-10-29 12:18:46.973 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
ValueError: Sensor sensor.knmi_thuis_dauwpunt has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'onb.' (<class 'str'>)
2023-10-29 12:19:16.974 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
2023-10-29 12:19:16.975 WARNING (MainThread) [custom_components.knmi] Value lv is empty in API response
2023-10-29 12:19:46.974 WARNING (MainThread) [custom_components.knmi] Value dauwp can't be converted to <class 'float'>
```

### Diagnostics

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.59",
    "supervisor": "2023.10.1",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "car_wash": {
      "version": "1.5.5",
      "requirements": []
    },
    "syncthru": {
      "version": "0.2.0",
      "requirements": [
        "pysyncthru==0.7.10",
        "url-normalize==1.4.3"
      ]
    },
    "knmi": {
      "version": "1.6.1",
      "requirements": []
    },
    "ventoptimization": {
      "version": "0.5",
      "requirements": []
    },
    "worlds_air_quality_index": {
      "version": "1.0.2",
      "requirements": []
    },
    "feedparser": {
      "version": "0.1.11",
      "requirements": [
        "feedparser==6.0.10"
      ]
    },
    "places": {
      "version": "v2.5.2.1",
      "requirements": []
    },
    "luchtmeetnet": {
      "version": "0.0.3",
      "requirements": [
        "luchtmeetnet==0.0.2"
      ]
    },
    "sun2": {
      "version": "2.4.0",
      "requirements": []
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ics_calendar": {
      "version": "4.0.1",
      "requirements": [
        "ics>=0.7.2",
        "recurring_ical_events>=2.0.2",
        "icalendar>=5.0.4"
      ]
    },
    "met_next_6_hours_forecast": {
      "version": "v1.1.0",
      "requirements": []
    },
    "buienalarm": {
      "version": "1.9",
      "requirements": [
        "pybuienalarm==0.1.1"
      ]
    },
    "neerslag": {
      "version": "2022.07.07.1",
      "requirements": []
    },
    "chime_tts": {
      "version": "v0.7.5",
      "requirements": [
        "pydub"
      ]
    },
    "powercalc": {
      "version": "v1.9.6",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "p2000": {
      "version": "1.0.23",
      "requirements": [
        "feedparser"
      ]
    },
    "holidays": {
      "version": "1.9.6",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.14.2"
      ]
    },
    "better_thermostat": {
      "version": "1.3.0",
      "requirements": []
    },
    "multiscrape": {
      "version": "6.5.0",
      "requirements": [
        "lxml==4.9.1",
        "beautifulsoup4==4.11.1"
      ]
    },
    "brandstofprijzen": {
      "version": "0.3.0",
      "requirements": [
        "beautifulsoup4==4.10.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "knmi",
    "name": "KNMI",
    "codeowners": [
      "@golles"
    ],
    "config_flow": true,
    "documentation": "https://github.com/golles/ha-knmi/blob/main/README.md",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/golles/ha-knmi/issues",
    "version": "1.6.1",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "df214dc5dd9e14a203c1c3c68634919e",
      "version": 1,
      "domain": "knmi",
      "title": "Thuis",
      "data": {
        "name": "Thuis",
        "latitude": "**REDACTED**",
        "longitude": "**REDACTED**",
        "api_key": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "data": {
      "plaats": "Capelle aan den IJssel",
      "timestamp": "1698691997",
      "time": "30-10-2023 19:53",
      "temp": "10.5",
      "gtemp": "10.5",
      "samenv": "Lichte motregen",
      "lv": "93",
      "windr": "NNO",
      "windrgr": "22",
      "windms": "1",
      "winds": "1",
      "windk": "1.9",
      "windkmh": "3.6",
      "luchtd": "995.7",
      "ldmmhg": "747",
      "dauwp": "9",
      "zicht": "11",
      "verw": "Op steeds meer plaatsen regen",
      "sup": "07:31",
      "sunder": "17:20",
      "image": "buien",
      "d0weer": "bewolkt",
      "d0tmax": "14",
      "d0tmin": "9",
      "d0windk": "3",
      "d0windknp": "8",
      "d0windms": "4",
      "d0windkmh": "15",
      "d0windr": "ZO",
      "d0windrgr": "135",
      "d0neerslag": "8",
      "d0zon": "11",
      "d1weer": "halfbewolkt_regen",
      "d1tmax": "13",
      "d1tmin": "8",
      "d1windk": "2",
      "d1windknp": "6",
      "d1windms": "3",
      "d1windkmh": "11",
      "d1windr": "ZW",
      "d1windrgr": "225",
      "d1neerslag": "70",
      "d1zon": "30",
      "d2weer": "halfbewolkt_regen",
      "d2tmax": "15",
      "d2tmin": "8",
      "d2windk": "3",
      "d2windknp": "8",
      "d2windms": "4",
      "d2windkmh": "15",
      "d2windr": "Z",
      "d2windrgr": "180",
      "d2neerslag": "70",
      "d2zon": "10",
      "alarm": "0",
      "alarmtxt": ""
    }
  }
}
```

**Comment by golles** [comment] 2023-10-30 20:33
Hi, what you're seeing is that data is missing from the API, that's why you get these messages, so you are aware of inconsistent data.
Duplicate of #99 

Also, what you're seeing are warnings, not errors.

**Closed by golles** 2023-10-30 20:33 UTC
Labels: bug

**Comment by golles** [comment] 2023-10-30 20:35
Looking at your diagnostics, it should've resolved, since `lv` and `dauwp` both have a value
