### ISSUE TITLE
Error in logging

### ISSUE THREAD

**Issue by edegraaff** [golles/ha-knmi#12] opened 2021-12-19 20:13 UTC
Seems version 1.0

I get after the last update this error in the log:
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 21:02:24 (8 occurrences)
Last logged: 21:09:16

Unable to prepare setup for platform knmi.binary_sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform knmi.weather: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform knmi.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

## Debug log

Do you want me to deliver an debug log ? 

```text
Add your logs here.
Seems also an item is gone in the config
![image](https://user-images.githubusercontent.com/12442749/146689361-cccec0c8-5b60-4d26-9bc8-4d67210ddd28.png)

Regards
Eelco
```

**Comment by golles** [comment] 2021-12-19 23:09
You need Home Assistant 2021.12 to use version 1.1.4 of this component. Or, if you don't want to update, you can use this branch with a temp fix: https://github.com/golles/ha-knmi/tree/2021.11-fix

Duplicate of #11

**Closed by golles** 2021-12-19 23:09 UTC

**Comment by edegraaff** [comment] 2021-12-20 09:22
updated and working , thanks !
